# Generated by Django 3.1.6 on 2021-04-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GFL', '0002_auto_20210401_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_datials',
            new_name='tournament_detials',
        ),
    ]
