# Generated by Django 3.1.6 on 2021-04-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GFL', '0003_auto_20210405_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
