# Generated by Django 3.1.6 on 2021-04-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFL', '0004_auto_20210405_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
